# Generated by Django 4.2.2 on 2023-06-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='restaurants_id',
            new_name='id',
        ),
    ]
