# Generated by Django 4.2.2 on 2023-06-27 11:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('searching_app', '0004_alter_restaurants_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='items',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
